name: Broken Links Checker

on:
  schedule:
    - cron: 0 8 * * * # Run daily at 8am
  workflow_dispatch:
 
env:
  SITE_URL: https://webhostingcompare.com/
  
jobs:
  check:
    name: Broken links checker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 14

      - uses: gautamkrishnar/keepalive-workflow@v2

      # https://github.com/stevenvachon/broken-link-checker
      - name: Install broken link checker
        run: npm install broken-link-checker -g

      - name: Check for broken links
        run: blc ${{ env.SITE_URL }} -ro --exclude 'https://twitter.com' --exclude 'https://www.uber.com' --exclude 'https://www.arvixe.com'
 
