name: Page Speed Insights

on:
  schedule:
    - cron: 0 8 * * * # Run daily at 8am
  workflow_dispatch:

env:
  SITE_URL: https://webhostingcompare.com/
  THRESHOLD: 80
  
jobs:

  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        strategy:
          - desktop
          - mobile
          
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.2
        id: psi
        with:
          url: ${{ env.SITE_URL }}
          threshold: ${{ env.THRESHOLD }}
          strategy: ${{ matrix.strategy }}
          key: ${{ secrets.PAGESPEEDINSIGHTS_APIKEY }}
